# Generated by Django 3.2.9 on 2022-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20220422_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.posting'),
        ),
    ]
